// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: user_event.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEventType int32

const (
	UserEventType_CREATED UserEventType = 0
	UserEventType_UPDATED UserEventType = 1
	UserEventType_DELETED UserEventType = 2
)

// Enum value maps for UserEventType.
var (
	UserEventType_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "DELETED",
	}
	UserEventType_value = map[string]int32{
		"CREATED": 0,
		"UPDATED": 1,
		"DELETED": 2,
	}
)

func (x UserEventType) Enum() *UserEventType {
	p := new(UserEventType)
	*p = x
	return p
}

func (x UserEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_event_proto_enumTypes[0].Descriptor()
}

func (UserEventType) Type() protoreflect.EnumType {
	return &file_user_event_proto_enumTypes[0]
}

func (x UserEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type UserEvent struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventType    UserEventType          `protobuf:"varint,1,opt,name=event_type,json=eventType,enum=users.UserEventType"`
	xxx_hidden_EventId      *string                `protobuf:"bytes,2,opt,name=event_id,json=eventId"`
	xxx_hidden_UserId       *string                `protobuf:"bytes,3,opt,name=user_id,json=userId"`
	xxx_hidden_UserName     *string                `protobuf:"bytes,4,opt,name=user_name,json=userName"`
	xxx_hidden_UserEmail    *string                `protobuf:"bytes,5,opt,name=user_email,json=userEmail"`
	xxx_hidden_UserTimezone *string                `protobuf:"bytes,6,opt,name=user_timezone,json=userTimezone"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_user_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserEvent) GetEventType() UserEventType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_EventType
		}
	}
	return UserEventType_CREATED
}

func (x *UserEvent) GetEventId() string {
	if x != nil {
		if x.xxx_hidden_EventId != nil {
			return *x.xxx_hidden_EventId
		}
		return ""
	}
	return ""
}

func (x *UserEvent) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *UserEvent) GetUserName() string {
	if x != nil {
		if x.xxx_hidden_UserName != nil {
			return *x.xxx_hidden_UserName
		}
		return ""
	}
	return ""
}

func (x *UserEvent) GetUserEmail() string {
	if x != nil {
		if x.xxx_hidden_UserEmail != nil {
			return *x.xxx_hidden_UserEmail
		}
		return ""
	}
	return ""
}

func (x *UserEvent) GetUserTimezone() string {
	if x != nil {
		if x.xxx_hidden_UserTimezone != nil {
			return *x.xxx_hidden_UserTimezone
		}
		return ""
	}
	return ""
}

func (x *UserEvent) SetEventType(v UserEventType) {
	x.xxx_hidden_EventType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *UserEvent) SetEventId(v string) {
	x.xxx_hidden_EventId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *UserEvent) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *UserEvent) SetUserName(v string) {
	x.xxx_hidden_UserName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *UserEvent) SetUserEmail(v string) {
	x.xxx_hidden_UserEmail = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *UserEvent) SetUserTimezone(v string) {
	x.xxx_hidden_UserTimezone = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *UserEvent) HasEventType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserEvent) HasEventId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserEvent) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserEvent) HasUserName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserEvent) HasUserEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UserEvent) HasUserTimezone() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UserEvent) ClearEventType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EventType = UserEventType_CREATED
}

func (x *UserEvent) ClearEventId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EventId = nil
}

func (x *UserEvent) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UserId = nil
}

func (x *UserEvent) ClearUserName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_UserName = nil
}

func (x *UserEvent) ClearUserEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_UserEmail = nil
}

func (x *UserEvent) ClearUserTimezone() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_UserTimezone = nil
}

type UserEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventType    *UserEventType
	EventId      *string
	UserId       *string
	UserName     *string
	UserEmail    *string
	UserTimezone *string
}

func (b0 UserEvent_builder) Build() *UserEvent {
	m0 := &UserEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EventType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_EventType = *b.EventType
	}
	if b.EventId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_EventId = b.EventId
	}
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_UserId = b.UserId
	}
	if b.UserName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_UserName = b.UserName
	}
	if b.UserEmail != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_UserEmail = b.UserEmail
	}
	if b.UserTimezone != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_UserTimezone = b.UserTimezone
	}
	return m0
}

var File_user_event_proto protoreflect.FileDescriptor

const file_user_event_proto_rawDesc = "" +
	"\n" +
	"\x10user_event.proto\x12\x05users\"\xd5\x01\n" +
	"\tUserEvent\x123\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x14.users.UserEventTypeR\teventType\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"user_email\x18\x05 \x01(\tR\tuserEmail\x12#\n" +
	"\ruser_timezone\x18\x06 \x01(\tR\fuserTimezone*6\n" +
	"\rUserEventType\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02B\vZ\t/internalb\beditionsp\xe8\a"

var file_user_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_event_proto_goTypes = []any{
	(UserEventType)(0), // 0: users.UserEventType
	(*UserEvent)(nil),  // 1: users.UserEvent
}
var file_user_event_proto_depIdxs = []int32{
	0, // 0: users.UserEvent.event_type:type_name -> users.UserEventType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_event_proto_init() }
func file_user_event_proto_init() {
	if File_user_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_event_proto_rawDesc), len(file_user_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_event_proto_goTypes,
		DependencyIndexes: file_user_event_proto_depIdxs,
		EnumInfos:         file_user_event_proto_enumTypes,
		MessageInfos:      file_user_event_proto_msgTypes,
	}.Build()
	File_user_event_proto = out.File
	file_user_event_proto_goTypes = nil
	file_user_event_proto_depIdxs = nil
}
