region := env("AWS_REGION", "eu-central-1")
tf-bin := env("TF_BIN", "tofu") # for tofu tflocal: TF_BIN=tflocal TF_CMD=tofu

export AWS_REGION := region

[working-directory: "infra/artifacts"]
artifacts-apply:
    {{tf-bin}} init && {{tf-bin}} apply -auto-approve

[working-directory: "infra/artifacts"]
artifacts-destroy:
    {{tf-bin}} destroy -auto-approve

[working-directory: "golang"]
golang-build:
    GOOS=linux GOARCH=arm64 go build -o dunno main.go

[working-directory: "golang"]
golang-clean:
    rm -f dunno